[General]
DebugLogLevel = info
TcpServerPort = 0

# Leave to TCP if using SITL
# Main connection to AutoPilot
[UartEndpoint cube]
Device = /dev/ttyACM0
Baud = 115200

# GCS USB
[UdpEndpoint gcs_usb]
Mode = Normal
# Address = 10.42.0.1
Address = 192.168.55.100
Port = 14550

# GCS Radio
[UdpEndpoint gcs_radio]
Mode = Server
Address = 0.0.0.0
Port = 14550

# AV Mavlink Configuration
[UdpEndpoint av_mavlink_configuration]
Mode = Normal
Address = 127.0.0.1
Port = 14590

# QGround configuration
[UdpEndpoint hotspot]
Mode = Normal
Address = 10.42.0.100
Port = 14513

# QGround configuration
[UdpEndpoint gcs_hotspot]
Mode = Normal
Address = 10.42.0.100
Port = 14550

# wifi configuration
[UdpEndpoint wifi]
Mode = Normal 
Address = 192.168.18.100
Port = 14513

# QGround configuration
[UdpEndpoint gcs_wifi]
Mode = Normal 
Address = 192.168.18.100
Port = 14550
